
; --- Project details
name             = CPAN-Testers-MCP
author           = Doug Bell <preaction@cpan.org>
license          = Perl_5
copyright_holder = Doug Bell
copyright_year   = 2026

[Authority]
authority  = cpan:PREACTION
do_munging = 0

[GithubMeta]
;homepage = http://preaction.me/project
issues = 1
[MetaResources]
;IRC                     = irc://irc.perl.org/#channel

[@Author::CPANTesters]

; --- Project-specific directives

[Prereqs]
perl = 5.040
Mojolicious = 9
MCP = 0.08
Test2::V1 = 1.302219
